<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>DshLauncher</RootNamespace>
    <AssemblyName>dsh-launcher</AssemblyName>
    <Version>0.3.7</Version>
    <AssemblyVersion>0.3.7.0</AssemblyVersion>
    <FileVersion>0.3.7.0</FileVersion>
    <InformationalVersion>0.3.7</InformationalVersion>
    <ApplicationIcon>..\..\assets\dsh-launcher.ico</ApplicationIcon>
    <Platforms>AnyCPU</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="DshLauncher.Tests" />
    <EmbeddedResource Include="..\..\assets\dsh-launcher.ico">
      <LogicalName>DshLauncher.Assets.dsh-launcher.ico</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\assets\sponsor-alipay.png">
      <LogicalName>DshLauncher.Assets.sponsor-alipay.png</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\assets\sponsor-wechat.png">
      <LogicalName>DshLauncher.Assets.sponsor-wechat.png</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
</Project>
