<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>DshLauncher</RootNamespace>
    <AssemblyName>dsh-launcher</AssemblyName>
    <Platforms>AnyCPU</Platforms>
  </PropertyGroup>
</Project>
